sudo: false

language: perl

perl:
  - "5.40"
  - "5.38"
  - "5.36"
  - "5.34"
  - "5.32"
  - "5.30"
  - "5.28"
  - "5.26"

matrix:
  include:
    - perl: "5.26"
      env: COVERAGE=1

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V

install:
  - cpan-install --coverage
  - cpanm --installdeps --notest --with-develop --with-feature=Data::Password --with-feature=ldap --with-feature=safe-unicode --with-feature=smime --with-feature=soap --with-feature=sqlite .

before_script:
  - coverage-setup

script:
  - autoreconf -i
  - ./configure
  - cd src; make; cd ..
  - make check-local TEST_FILES='xt/perltidy.t' || true
  - make check-local

after_success:
  - coverage-report

